In [1]:
import pandas as pd

In [2]:
stock_df = pd.read_csv('../data/raw/hourly_stock_data.csv')
df_hourly = pd.read_csv('../data/test/hourly_historical_weather.csv')

In [3]:
df_hourly["time"] = pd.to_datetime(df_hourly["time"])

df_hourly["time"] = df_hourly["time"].dt.strftime("%Y-%m-%d %H:%M:%S")

df_hourly["time"] = df_hourly["time"].astype(str)

df_hourly

,time,date,time_epoch,temp_c,temp_f,is_day,condition_text,condition_icon,condition_code,wind_mph,...,dewpoint_f,will_it_rain,chance_of_rain,will_it_snow,chance_of_snow,vis_km,vis_miles,gust_mph,gust_kph,uv
0,2024-12-24 00:00:00,2024-12-24,1735016400,-3.2,26.3,0,NaN,NaN,0,8.9,...,20.1,0,0,0,0,10.0,6.0,13.1,21.1,0.0
1,2024-12-24 01:00:00,2024-12-24,1735020000,-3.3,26.1,0,NaN,NaN,0,9.4,...,20.0,0,0,0,0,10.0,6.0,13.7,22.0,0.0
2,2024-12-24 02:00:00,2024-12-24,1735023600,-3.2,26.3,0,NaN,NaN,0,9.4,...,19.9,0,0,0,0,10.0,6.0,13.6,21.9,0.0
3,2024-12-24 03:00:00,2024-12-24,1735027200,-3.1,26.5,0,NaN,NaN,0,9.4,...,20.8,0,0,0,0,10.0,6.0,13.8,22.2,0.0
4,2024-12-24 04:00:00,2024-12-24,1735030800,-2.9,26.7,0,NaN,NaN,0,9.6,...,21.3,0,0,0,0,10.0,6.0,14.2,22.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2179,2024-11-23 19:00:00,2024-11-23,1732406400,7.1,44.8,0,NaN,NaN,0,14.1,...,34.4,0,0,0,0,10.0,6.0,19.7,31.7,0.0
2180,2024-11-23 20:00:00,2024-11-23,1732410000,7.1,44.8,0,NaN,NaN,0,15.0,...,34.4,0,0,0,0,10.0,6.0,21.2,34.1,0.0
2181,2024-11-23 21:00:00,2024-11-23,1732413600,7.2,45.0,0,NaN,NaN,0,13.4,...,36.3,0,0,0,0,10.0,6.0,19.3,31.0,0.0
2182,2024-11-23 22:00:00,2024-11-23,1732417200,6.7,44.1,0,NaN,NaN,0,12.5,...,37.2,0,0,0,0,10.0,6.0,18.0,28.9,0.0
2183,2024-11-23 23:00:00,2024-11-23,1732420800,6.9,44.4,0,NaN,NaN,0,13.6,...,39.5,0,0,0,0,10.0,6.0,20.6,33.2,0.0

In [4]:
# Convert 'timestamp' column to datetime format
stock_df['timestamp'] = pd.to_datetime(stock_df['timestamp'])

# Round to the nearest hour
stock_df['timestamp'] = stock_df['timestamp'].dt.round('h')


# Drop duplicates, keeping the first occurrence
stock_df.drop_duplicates(subset=['timestamp'], keep='first', inplace=True, ignore_index=True)

stock_df['timestamp'] = stock_df['timestamp'].astype(str)

stock_df

             timestamp      open      high       low     close  volume
0  2025-01-22 20:00:00  222.6500  222.6500  222.5000  222.5000      67
1  2025-01-22 19:00:00  222.5185  222.5185  222.5185  222.5185       2
2  2025-01-22 18:00:00  223.2600  223.2600  223.2600  223.2600  547325
3  2025-01-22 17:00:00  223.2340  223.2340  223.2000  223.2000      30
4  2025-01-22 16:00:00  223.0500  223.2600  223.0500  223.2600    3524
5  2025-01-22 15:00:00  223.4450  223.4450  223.0600  223.0600   44503
6  2025-01-22 14:00:00  223.6750  223.9400  223.6750  223.8917    7922
7  2025-01-22 13:00:00  223.7100  223.8200  223.6000  223.6400   22666
8  2025-01-22 12:00:00  222.7500  223.0300  222.6850  222.8053   28636
9  2025-01-22 11:00:00  221.7550  222.2800  221.6813  222.1750   34654

In [5]:
# Merge the DataFrames on 'time' and 'timestamp'
merged_df = pd.merge(df_hourly, stock_df, left_on='time', right_on='timestamp', how='inner')

# Drop one of the duplicate datetime columns if needed
merged_df.drop(columns=['timestamp'], inplace=True)

merged_df

,time,date,time_epoch,temp_c,temp_f,is_day,condition_text,condition_icon,condition_code,wind_mph,...,vis_km,vis_miles,gust_mph,gust_kph,uv,open,high,low,close,volume
0,2025-01-22 11:00:00,2025-01-22,1737561600,-7.9,17.8,1,NaN,NaN,0,8.9,...,10.0,6.0,11.3,18.1,2.0,221.7550,222.2800,221.6813,222.1750,34654
1,2025-01-22 12:00:00,2025-01-22,1737565200,-7.1,19.3,1,NaN,NaN,0,8.1,...,10.0,6.0,9.9,16.0,2.0,222.7500,223.0300,222.6850,222.8053,28636
2,2025-01-22 13:00:00,2025-01-22,1737568800,-6.3,20.6,1,NaN,NaN,0,7.4,...,10.0,6.0,8.9,14.3,2.0,223.7100,223.8200,223.6000,223.6400,22666
3,2025-01-22 14:00:00,2025-01-22,1737572400,-5.5,22.1,1,NaN,NaN,0,8.3,...,10.0,6.0,9.6,15.5,2.0,223.6750,223.9400,223.6750,223.8917,7922
4,2025-01-22 15:00:00,2025-01-22,1737576000,-4.8,23.3,1,NaN,NaN,0,7.8,...,10.0,6.0,9.3,15.0,2.0,223.4450,223.4450,223.0600,223.0600,44503
5,2025-01-22 16:00:00,2025-01-22,1737579600,-4.3,24.3,1,NaN,NaN,0,8.1,...,10.0,6.0,9.9,15.9,2.0,223.0500,223.2600,223.0500,223.2600,3524
6,2025-01-22 17:00:00,2025-01-22,1737583200,-4.9,23.3,1,NaN,NaN,0,6.9,...,10.0,6.0,8.9,14.4,2.0,223.2340,223.2340,223.2000,223.2000,30
7,2025-01-22 18:00:00,2025-01-22,1737586800,-5.6,21.9,0,NaN,NaN,0,5.8,...,10.0,6.0,7.9,12.7,0.0,223.2600,223.2600,223.2600,223.2600,547325
8,2025-01-22 19:00:00,2025-01-22,1737590400,-6.4,20.5,0,NaN,NaN,0,4.9,...,10.0,6.0,6.6,10.7,0.0,222.5185,222.5185,222.5185,222.5185,2
9,2025-01-22 20:00:00,2025-01-22,1737594000,-6.9,19.6,0,NaN,NaN,0,4.0,...,10.0,6.0,5.6,9.0,0.0,222.6500,222.6500,222.5000,222.5000,67

In [6]:
daily_stock = pd.read_csv('../data/raw/daily_stock_data.csv')
daily_weather = pd.read_csv('../data/test/daily_historical_weather.csv')

In [7]:
daily_stock

     timestamp     open      high       low   close   volume
0   2025-01-22  221.980  224.4000  220.3500  223.26  4759490
1   2025-01-21  224.990  227.4500  222.8302  224.26  3982203
2   2025-01-17  225.955  225.9550  223.6400  224.79  5506837
3   2025-01-16  219.690  222.6800  217.3800  222.66  3329060
4   2025-01-15  220.870  221.6761  218.0100  220.03  2951825
..         ...      ...       ...       ...     ...      ...
95  2024-09-04  200.760  204.3600  200.5000  204.11  3111332
96  2024-09-03  201.910  204.7200  200.2100  201.28  3874697
97  2024-08-30  199.110  202.1700  198.7300  202.13  4750999
98  2024-08-29  199.300  201.1200  198.2700  198.90  2989594
99  2024-08-28  199.000  200.0000  197.4900  198.46  2645244

[100 rows x 6 columns]

In [8]:
daily_weather

,date,location_name,location_region,location_country,location_lat,location_lon,location_tz_id,location_localtime,date_epoch,maxtemp_c,...,condition_text,condition_icon,condition_code,uv,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,2024-12-24,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1734998400,1.9,...,Overcast,//cdn.weatherapi.com/weather/64x64/day/122.png,1009,1.0,07:18 AM,04:34 PM,01:13 AM,12:25 PM,Waning Crescent,38
1,2024-12-25,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735084800,2.1,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000,2.0,07:19 AM,04:34 PM,02:14 AM,12:46 PM,Waning Crescent,29
2,2024-12-26,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735171200,1.8,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000,2.0,07:19 AM,04:35 PM,03:17 AM,01:12 PM,Waning Crescent,21
3,2024-12-27,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735257600,2.9,...,Partly cloudy,//cdn.weatherapi.com/weather/64x64/day/116.png,1003,2.0,07:19 AM,04:36 PM,04:21 AM,01:42 PM,Waning Crescent,14
4,2024-12-28,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735344000,7.5,...,Heavy rain,//cdn.weatherapi.com/weather/64x64/day/308.png,1195,2.0,07:20 AM,04:36 PM,05:27 AM,02:20 PM,Waning Crescent,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,2024-11-19,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731974400,13.3,...,Partly cloudy,//cdn.weatherapi.com/weather/64x64/day/116.png,1003,4.0,06:48 AM,04:34 PM,08:01 PM,11:04 AM,Waning Gibbous,86
87,2024-11-20,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732060800,11.5,...,Overcast,//cdn.weatherapi.com/weather/64x64/day/122.png,1009,3.0,06:49 AM,04:34 PM,09:11 PM,11:46 AM,Waning Gibbous,77
88,2024-11-21,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732147200,11.0,...,Heavy rain,//cdn.weatherapi.com/weather/64x64/day/308.png,1195,3.0,06:50 AM,04:33 PM,10:18 PM,12:18 PM,Waning Gibbous,68
89,2024-11-22,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732233600,8.2,...,Overcast,//cdn.weatherapi.com/weather/64x64/day/122.png,1009,2.0,06:52 AM,04:33 PM,11:23 PM,12:43 PM,Last Quarter,58
90,2024-11-23,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732320000,8.3,...,Overcast,//cdn.weatherapi.com/weather/64x64/day/122.png,1009,2.0,06:53 AM,04:32 PM,No moonrise,01:06 PM,Waning Crescent,49

In [9]:
merged_df = pd.merge(
        daily_weather,
        daily_stock,
        left_on="date",
        right_on="timestamp",
        how="inner",
    )

merged_df.drop(columns=["timestamp"], inplace=True)

merged_df

,date,location_name,location_region,location_country,location_lat,location_lon,location_tz_id,location_localtime,date_epoch,maxtemp_c,...,sunset,moonrise,moonset,moon_phase,moon_illumination,open,high,low,close,volume
0,2024-12-24,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1734998400,1.9,...,04:34 PM,01:13 AM,12:25 PM,Waning Crescent,38,222.270,224.4446,221.5428,224.41,1186216
1,2024-12-26,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735171200,1.8,...,04:35 PM,03:17 AM,01:12 PM,Waning Crescent,21,223.310,225.4000,222.5500,224.89,3287238
2,2024-12-27,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735257600,2.9,...,04:36 PM,04:21 AM,01:42 PM,Waning Crescent,14,223.140,224.4200,221.4054,222.78,1810760
3,2024-12-30,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735516800,11.9,...,04:38 PM,07:29 AM,04:07 PM,New Moon,1,220.540,221.5942,217.6523,220.25,2095565
4,2024-12-31,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735603200,8.7,...,04:39 PM,08:19 AM,05:15 PM,Waxing Crescent,0,220.720,221.0493,218.4400,219.83,2270512
5,2025-01-02,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735776000,5.6,...,04:40 PM,09:35 AM,07:42 PM,Waxing Crescent,6,221.820,222.4900,217.6000,219.94,2579498
6,2025-01-03,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1735862400,4.0,...,04:41 PM,10:04 AM,08:55 PM,Waxing Crescent,12,220.550,223.6600,220.5500,222.65,3873578
7,2025-01-06,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736121600,-0.7,...,04:44 PM,11:15 AM,No moonset,First Quarter,41,223.000,224.3500,220.7500,222.67,2847128
8,2025-01-07,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736208000,-0.9,...,04:45 PM,11:39 AM,12:32 AM,Waxing Gibbous,52,223.350,226.7110,222.8300,223.96,3299701
9,2025-01-08,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736294400,-0.3,...,04:46 PM,12:07 PM,01:47 AM,Waxing Gibbous,64,223.910,224.9000,220.8300,223.18,2619768
10,2025-01-10,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736467200,0.3,...,04:48 PM,01:24 PM,04:19 AM,Waxing Gibbous,83,222.000,222.4300,216.8000,219.75,3570497
11,2025-01-13,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736726400,5.0,...,04:51 PM,04:28 PM,07:28 AM,Full Moon,99,217.890,219.5900,214.7500,217.40,3716816
12,2025-01-14,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736812800,-0.5,...,04:53 PM,05:40 PM,08:09 AM,Waning Gibbous,100,218.000,218.1250,214.6100,217.75,3485829
13,2025-01-15,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736899200,1.4,...,04:54 PM,06:49 PM,08:42 AM,Waning Gibbous,98,220.870,221.6761,218.0100,220.03,2951825
14,2025-01-16,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1736985600,-0.8,...,04:55 PM,07:56 PM,09:08 AM,Waning Gibbous,94,219.690,222.6800,217.3800,222.66,3329060
15,2025-01-17,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1737072000,2.4,...,04:56 PM,08:59 PM,09:30 AM,Waning Gibbous,89,225.955,225.9550,223.6400,224.79,5506837
16,2025-01-21,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1737417600,-7.0,...,05:01 PM,12:01 AM,10:48 AM,Last Quarter,56,224.990,227.4500,222.8302,224.26,3982203
17,2025-01-22,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1737504000,-4.3,...,05:02 PM,01:03 AM,11:12 AM,Waning Crescent,47,221.980,224.4000,220.3500,223.26,4759490
18,2024-11-25,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1732492800,10.6,...,04:31 PM,01:25 AM,01:44 PM,Waning Crescent,30,223.350,226.4200,222.6500,226.13,7189260
19,2024-11-26,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1732579200,12.1,...,04:31 PM,02:24 AM,02:02 PM,Waning Crescent,22,226.730,228.9800,225.5115,228.83,4449543
20,2024-11-27,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1732665600,7.4,...,04:30 PM,03:24 AM,02:22 PM,Waning Crescent,15,228.830,229.1900,224.2700,226.92,2995121
21,2024-11-29,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1732838400,5.8,...,04:29 PM,05:30 AM,03:12 PM,Waning Crescent,4,227.750,230.3600,227.1900,227.41,2640253
22,2024-12-02,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733097600,4.6,...,04:29 PM,08:42 AM,05:18 PM,Waxing Crescent,1,227.500,228.3800,225.5100,227.39,2656181
23,2024-12-03,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733184000,4.4,...,04:28 PM,09:37 AM,06:18 PM,Waxing Crescent,4,227.240,229.1100,226.6700,229.00,3163815
24,2024-12-04,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733270400,2.3,...,04:28 PM,10:23 AM,07:27 PM,Waxing Crescent,9,230.000,233.7400,229.3500,233.49,4104195
25,2024-12-05,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733356800,2.4,...,04:28 PM,11:02 AM,08:38 PM,Waxing Crescent,16,233.550,236.5200,233.4600,234.75,4791116
26,2024-12-06,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733443200,2.1,...,04:28 PM,11:33 AM,09:51 PM,Waxing Crescent,24,234.430,238.3800,234.2200,238.04,4028430
27,2024-12-09,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733702400,7.5,...,04:28 PM,12:47 PM,12:15 AM,Waxing Gibbous,56,238.000,239.3500,228.9100,230.00,4970449
28,2024-12-10,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733788800,10.6,...,04:28 PM,01:11 PM,01:29 AM,Waxing Gibbous,67,228.400,234.3900,227.8000,231.72,4769531
29,2024-12-11,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733875200,12.8,...,04:28 PM,01:37 PM,02:43 AM,Waxing Gibbous,78,232.690,233.0000,229.1300,230.12,3872680
30,2024-12-12,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1733961600,5.3,...,04:29 PM,02:07 PM,04:01 AM,Waxing Gibbous,87,230.660,233.8900,230.3800,232.26,4515741
31,2024-12-13,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734048000,0.3,...,04:29 PM,02:45 PM,05:20 AM,Waxing Gibbous,94,232.250,233.7750,230.2600,230.82,2757683
32,2024-12-16,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734307200,11.4,...,04:30 PM,05:39 PM,08:50 AM,Waning Gibbous,99,230.730,231.0300,226.8800,229.33,3610257
33,2024-12-17,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734393600,12.0,...,04:30 PM,06:49 PM,09:38 AM,Waning Gibbous,96,229.230,230.2000,227.6200,228.97,3651346
34,2024-12-18,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734480000,7.5,...,04:30 PM,08:00 PM,10:14 AM,Waning Gibbous,90,229.035,229.0350,220.0300,220.17,4152517
35,2024-12-19,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734566400,6.3,...,04:31 PM,09:08 PM,10:43 AM,Waning Gibbous,83,224.420,226.2000,222.9800,223.92,4430120
36,2024-12-20,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734652800,3.3,...,04:31 PM,10:12 PM,11:07 AM,Waning Gibbous,75,222.730,227.6847,221.6800,223.36,12423200
37,2024-12-23,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:41,1734912000,-0.6,...,04:33 PM,12:13 AM,12:06 PM,Waning Crescent,47,222.810,223.7400,221.0800,221.93,2988137
38,2024-10-25,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1729814400,15.5,...,06:01 PM,12:25 AM,03:17 PM,Waning Crescent,41,216.800,218.6500,214.3850,214.67,8482235
39,2024-10-28,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730073600,17.8,...,05:57 PM,03:34 AM,04:20 PM,Waning Crescent,16,215.500,216.2500,212.7000,212.91,4993343
40,2024-10-29,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730160000,15.1,...,05:55 PM,04:33 AM,04:38 PM,Waning Crescent,10,211.990,213.3400,209.8500,210.43,5258366
41,2024-10-30,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730246400,18.6,...,05:54 PM,05:33 AM,04:57 PM,Waning Crescent,5,209.480,211.1200,204.2600,204.90,6956624
42,2024-10-31,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730332800,23.5,...,05:53 PM,06:33 AM,05:18 PM,Waning Crescent,2,204.130,208.1300,203.5100,206.72,5925250
43,2024-11-01,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730419200,20.3,...,05:52 PM,07:36 AM,05:42 PM,New Moon,0,207.770,209.8400,207.4100,208.25,3334308
44,2024-11-04,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730678400,12.5,...,04:48 PM,09:49 AM,06:29 PM,Waxing Crescent,7,207.650,207.7000,205.8000,206.32,2594119
45,2024-11-05,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730764800,19.0,...,04:47 PM,10:48 AM,07:23 PM,Waxing Crescent,13,206.170,208.1150,205.5700,207.57,2441535
46,2024-11-06,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730851200,18.0,...,04:46 PM,11:41 AM,08:25 PM,Waxing Crescent,20,213.480,214.3300,210.3700,213.60,3934386
47,2024-11-07,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1730937600,21.0,...,04:45 PM,12:24 PM,09:35 PM,Waxing Crescent,29,213.640,214.5199,211.9300,213.69,3675812
48,2024-11-08,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731024000,18.6,...,04:44 PM,01:00 PM,10:47 PM,First Quarter,39,214.160,216.7000,212.7809,213.72,3201038
49,2024-11-11,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731283200,17.0,...,04:41 PM,02:21 PM,01:15 AM,Waxing Gibbous,71,214.400,215.4100,213.4800,213.57,3012987
50,2024-11-12,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731369600,12.2,...,04:40 PM,02:45 PM,02:30 AM,Waxing Gibbous,81,211.900,213.0300,209.0600,210.86,2818216
51,2024-11-13,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731456000,8.6,...,04:39 PM,03:10 PM,03:47 AM,Waxing Gibbous,90,209.500,211.4100,209.0701,210.92,3247830
52,2024-11-14,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731542400,7.9,...,04:38 PM,03:39 PM,05:06 AM,Waxing Gibbous,96,210.000,210.4999,206.3500,208.99,6372853
53,2024-11-15,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731628800,14.6,...,04:37 PM,04:13 PM,06:27 AM,Full Moon,99,207.460,208.4900,204.0700,204.99,3986460
54,2024-11-18,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731888000,16.9,...,04:35 PM,06:52 PM,10:11 AM,Waning Gibbous,93,207.000,208.4150,205.3701,208.09,3406045
55,2024-11-19,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1731974400,13.3,...,04:34 PM,08:01 PM,11:04 AM,Waning Gibbous,86,206.500,210.3300,206.1900,210.25,2860746
56,2024-11-20,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732060800,11.5,...,04:34 PM,09:11 PM,11:46 AM,Waning Gibbous,77,211.000,214.9600,209.7725,214.60,4562901
57,2024-11-21,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732147200,11.0,...,04:33 PM,10:18 PM,12:18 PM,Waning Gibbous,68,215.810,222.6300,215.2701,222.40,5236434
58,2024-11-22,New York,New York,United States of America,40.7142,-74.0064,America/New_York,2025-01-23 04:38,1732233600,8.2,...,04:33 PM,11:23 PM,12:43 PM,Last Quarter,58,223.350,227.2000,220.8900,222.97,5320740

In [10]:
current_stock = pd.read_csv('../data/raw/hourly_stock_data.csv')
current_weather = pd.read_csv('../data/processed/cleaned_current_weather.csv')

In [11]:
current_stock

              timestamp      open      high       low     close  volume
0   2025-01-22 19:55:00  222.6500  222.6500  222.5000  222.5000      67
1   2025-01-22 19:45:00  223.2215  223.2215  223.2215  223.2215       5
2   2025-01-22 19:35:00  222.8000  222.8100  222.6400  222.6400      69
3   2025-01-22 19:30:00  222.5000  222.8000  222.5000  222.8000      14
4   2025-01-22 19:25:00  222.5185  222.5185  222.5185  222.5185       2
..                  ...       ...       ...       ...       ...     ...
95  2025-01-22 11:15:00  221.2350  221.6120  221.0300  221.4300   41895
96  2025-01-22 11:10:00  221.3980  221.4400  220.9950  221.1900   44115
97  2025-01-22 11:05:00  220.9400  221.5800  220.8651  221.3736   73124
98  2025-01-22 11:00:00  221.0100  221.2899  220.8400  221.0000   49667
99  2025-01-22 10:55:00  221.0100  221.2400  220.7200  220.9000   43415

[100 rows x 6 columns]

In [12]:
current_weather

,local_time,location_name,region,country,lat,lon,tz_id,localtime_epoch,last_updated_epoch,last_updated,...,gust_mph,gust_kph,co,no2,o3,so2,pm2_5,pm10,us_epa_index,gb_defra_index
0,2025-01-22 14:55:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737575714,1737575100,2025-01-22 14:45:00.000,...,6.4,10.4,1237.65,109.335,16.0,22.015,68.265,71.780,4,9
1,2025-01-22 14:57:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737575876,1737575100,2025-01-22 14:45:00.000,...,6.4,10.4,1237.65,109.335,16.0,22.015,68.265,71.780,4,9
2,2025-01-22 15:39:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737578358,1737577800,2025-01-22 15:30:00.000,...,4.9,7.8,1487.40,136.160,0.0,27.195,77.700,81.215,4,10
3,2025-01-23 04:51:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737625915,1737625500,2025-01-23 04:45:00.000,...,7.2,11.5,1535.50,106.190,8.0,30.710,91.945,95.275,4,10
4,2025-01-23 05:04:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737626669,1737626400,2025-01-23 05:00:00.000,...,6.8,10.9,1387.50,93.240,18.0,30.895,88.430,91.760,4,10
5,2025-01-23 06:03:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737630219,1737630000,2025-01-23 06:00:00.000,...,6.7,10.8,1554.00,98.235,26.0,38.665,76.590,79.920,4,10
6,2025-01-23 07:05:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737633902,1737633600,2025-01-23 07:00:00.000,...,6.2,9.9,1319.05,83.990,37.0,35.705,59.940,62.900,3,8
7,2025-01-23 08:05:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737637502,1737637200,2025-01-23 08:00:00.000,...,6.2,10.0,987.90,69.005,49.0,30.895,49.950,52.725,3,6
8,2025-01-23 09:04:00.000,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737641057,1737640800,2025-01-23 09:00:00.000,...,7.1,11.4,747.40,59.200,56.0,27.010,42.735,45.510,3,5

In [14]:
def format_date(df, column="time"):
    # Convert 'time' column to datetime format
    df[column] = pd.to_datetime(df[column])

    # Format it to 'YYYY-MM-DD HH:MM:SS'
    df[column] = df[column].dt.strftime("%Y-%m-%d %H:%M:%S")

    # Convert back to object(string)
    df[column] = df[column].astype(str)

    return df


def floor_date_to_hour(df, column="timestamp"):
    # Convert 'timestamp' column to datetime format
    df[column] = pd.to_datetime(df[column])

    # Floor to nearest hour
    df[column] = df[column].dt.floor("H")

    # Drop duplicates, keeping the first occurrence
    df.drop_duplicates(subset=[column], keep="first", inplace=True, ignore_index=True)

    # Convert back to object(string)
    df[column] = df[column].astype(str)

    return df

def merge_current_stock_and_weather(weather, stock, file_name):
    formatted_weather = floor_date_to_hour(
        format_date(weather, column="local_time"), column="local_time"
    )
    formatted_stock = floor_date_to_hour(stock)

    # Merge the DataFrames on local_time and timestamp
    merged_df = pd.merge(
        formatted_weather,
        formatted_stock,
        left_on="local_time",
        right_on="timestamp",
        how="inner",
    )

    # Drop one of the duplicate datetime columns
    # merged_df.drop(columns=["timestamp"], inplace=True)

    return merged_df


merged_current_data = merge_current_stock_and_weather(
        current_weather, current_stock, "merged_current_data.csv"
    )

merged_current_data

C:\Users\afzal\AppData\Local\Temp\ipykernel_17924\647007468.py:19: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[column] = df[column].dt.floor("H")
C:\Users\afzal\AppData\Local\Temp\ipykernel_17924\647007468.py:19: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df[column] = df[column].dt.floor("H")

,local_time,location_name,region,country,lat,lon,tz_id,localtime_epoch,last_updated_epoch,last_updated,...,pm2_5,pm10,us_epa_index,gb_defra_index,timestamp,open,high,low,close,volume
0,2025-01-22 14:00:00,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737575714,1737575100,2025-01-22 14:45:00.000,...,68.265,71.780,4,9,2025-01-22 14:00:00,224.320,224.33,224.18,224.26,20214
1,2025-01-22 15:00:00,New York,New York,United States of America,40.7142,-74.0064,America/New_York,1737578358,1737577800,2025-01-22 15:30:00.000,...,77.700,81.215,4,10,2025-01-22 15:00:00,222.735,223.26,222.50,223.22,295326